config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.delete
    redirect_to articles_path
  end

  private

  def article_params
    # => Whitelisting
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :content %>
<%= f.text_field :content %>

<br>
<br>

<%= f.submit %>


<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div justify-content="center">
  <h1>My articles</h1>
</div>
<div>
  <ul>
  <% @articles.each do |article| %>

  <li>
    <h4> <%= link_to article.title,  article_path(article)%> </h4>
    <p> <%= article.content %></p>

  </li>

  <% end %>

  </ul>

</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<%= link_to "📋", edit_article_path(@article) %>
<%= link_to "🗑", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

<p> <%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-light bg-light">
      <%= link_to "New Article",  new_article_path%>
    </div>
    <%= yield %>
  </body>
</html>